export const rows = [
    {
        id: 1,
        registrarId: "R-10234",
        name: "Ahmed Youssef",
        age: 24,
        phone: "01093284756",
        email: "ahmed.youssef@gmail.com",
        address: "15 El-Nasr St",
        city: "Cairo",
        zipCode: "11511",
    },
    {
        id: 2,
        registrarId: "R-10456",
        name: "Sara Ali",
        age: 22,
        phone: "01157392014",
        email: "sara.ali@hotmail.com",
        address: "42 Tahrir Square",
        city: "Giza",
        zipCode: "12611",
    },
    {
        id: 3,
        registrarId: "R-10678",
        name: "Omar Khaled",
        age: 26,
        phone: "01267849302",
        email: "omar.khaled@yahoo.com",
        address: "9 Al-Maadi St",
        city: "Cairo",
        zipCode: "11728",
    },
    {
        id: 4,
        registrarId: "R-10901",
        name: "Mona Ibrahim",
        age: 21,
        phone: "01028473911",
        email: "mona.ibrahim@gmail.com",
        address: "6 Mostafa Kamel Rd",
        city: "Alexandria",
        zipCode: "21523",
    },
    {
        id: 5,
        registrarId: "R-11022",
        name: "Mahmoud Tarek",
        age: 25,
        phone: "01192837465",
        email: "mahmoud.tarek@outlook.com",
        address: "18 Port Said St",
        city: "Mansoura",
        zipCode: "35511",
    },
    {
        id: 6,
        registrarId: "R-11245",
        name: "Nour Hassan",
        age: 23,
        phone: "01254673829",
        email: "nour.hassan@gmail.com",
        address: "7 Omar Ibn El-Khattab St",
        city: "Zagazig",
        zipCode: "44519",
    },
    {
        id: 7,
        registrarId: "R-11389",
        name: "Khaled Samir",
        age: 27,
        phone: "01017384926",
        email: "khaled.samir@yahoo.com",
        address: "22 El-Gaish Rd",
        city: "Alexandria",
        zipCode: "21511",
    },
    {
        id: 8,
        registrarId: "R-11500",
        name: "Reem Adel",
        age: 22,
        phone: "01164739285",
        email: "reem.adel@hotmail.com",
        address: "33 El-Nozha St",
        city: "Cairo",
        zipCode: "11757",
    },
    {
        id: 9,
        registrarId: "R-11672",
        name: "Hassan Fathy",
        age: 29,
        phone: "01283947201",
        email: "hassan.fathy@gmail.com",
        address: "10 El-Salam Rd",
        city: "Tanta",
        zipCode: "31516",
    },
    {
        id: 10,
        registrarId: "R-11834",
        name: "Layla Magdy",
        age: 24,
        phone: "01098734562",
        email: "layla.magdy@yahoo.com",
        address: "8 Ahmed Orabi St",
        city: "Ismailia",
        zipCode: "41512",
    },
    {
        id: 11,
        registrarId: "R-11976",
        name: "Ola Mostafa",
        age: 28,
        phone: "01123459876",
        email: "ola.mostafa@gmail.com",
        address: "25 El-Horreya St",
        city: "Cairo",
        zipCode: "11641",
    },
    ];

    
export const columns = [
  { field: 'id', headerName: 'ID', width:50, align:"Center", headerAlign: "center" },
  { field: 'registrarId', name: 'Name',flex:1, align:"Center", headerAlign: "center"},
  { field: 'name', headerName: 'Name', flex:1, align:"Center", headerAlign: "center" },
  { field: 'age', headerName: 'Age', align:"Center", headerAlign: "center"},
  { field: 'phone', headerName: 'Phone Number', flex:1, align:"Center", headerAlign: "center" },
  { field: 'email', headerName: 'Email', flex:1, align:"Center", headerAlign: "center"  },
  { field: 'address', headerName: 'Address', flex:1, align:"Center", headerAlign: "center"  },
  { field: 'city', headerName: 'City', flex:1, align:"Center", headerAlign: "center"  },
  { field: 'zipCode', headerName: 'Zip Code', flex:1, align:"Center", headerAlign: "center"  },
];